/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DRCPFunctionsConsumerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "callbackGasLimit"
      | "donId"
      | "handleOracleFulfillment"
      | "latestRiskScore"
      | "owner"
      | "parametricVault"
      | "renounceOwnership"
      | "requestRiskScore"
      | "requests"
      | "setCallbackGasLimit"
      | "setParametricVault"
      | "setSourceCode"
      | "setSubscriptionId"
      | "sourceCode"
      | "subscriptionId"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RequestFulfilled"
      | "RequestSent"
      | "RiskScoreFulfilled"
      | "RiskScoreRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "callbackGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "donId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "handleOracleFulfillment",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestRiskScore",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "parametricVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRiskScore",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "requests", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setCallbackGasLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setParametricVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSourceCode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubscriptionId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sourceCode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "callbackGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleOracleFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parametricVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCallbackGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setParametricVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSourceCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubscriptionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sourceCode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestFulfilledEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestSentEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoreFulfilledEvent {
  export type InputTuple = [requestId: BytesLike, severity: BigNumberish];
  export type OutputTuple = [requestId: string, severity: bigint];
  export interface OutputObject {
    requestId: string;
    severity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoreRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    latitude: BigNumberish,
    longitude: BigNumberish,
    disasterType: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    latitude: bigint,
    longitude: bigint,
    disasterType: string
  ];
  export interface OutputObject {
    requestId: string;
    latitude: bigint;
    longitude: bigint;
    disasterType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DRCPFunctionsConsumer extends BaseContract {
  connect(runner?: ContractRunner | null): DRCPFunctionsConsumer;
  waitForDeployment(): Promise<this>;

  interface: DRCPFunctionsConsumerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callbackGasLimit: TypedContractMethod<[], [bigint], "view">;

  donId: TypedContractMethod<[], [string], "view">;

  handleOracleFulfillment: TypedContractMethod<
    [requestId: BytesLike, response: BytesLike, err: BytesLike],
    [void],
    "nonpayable"
  >;

  latestRiskScore: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  parametricVault: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestRiskScore: TypedContractMethod<
    [
      _latitude: BigNumberish,
      _longitude: BigNumberish,
      _disasterType: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, string, boolean] & {
        latitude: bigint;
        longitude: bigint;
        disasterType: string;
        fulfilled: boolean;
      }
    ],
    "view"
  >;

  setCallbackGasLimit: TypedContractMethod<
    [_gasLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setParametricVault: TypedContractMethod<
    [_vault: AddressLike],
    [void],
    "nonpayable"
  >;

  setSourceCode: TypedContractMethod<
    [_sourceCode: string],
    [void],
    "nonpayable"
  >;

  setSubscriptionId: TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  sourceCode: TypedContractMethod<[], [string], "view">;

  subscriptionId: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callbackGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "donId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "handleOracleFulfillment"
  ): TypedContractMethod<
    [requestId: BytesLike, response: BytesLike, err: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "latestRiskScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "parametricVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRiskScore"
  ): TypedContractMethod<
    [
      _latitude: BigNumberish,
      _longitude: BigNumberish,
      _disasterType: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, string, boolean] & {
        latitude: bigint;
        longitude: bigint;
        disasterType: string;
        fulfilled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setCallbackGasLimit"
  ): TypedContractMethod<[_gasLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setParametricVault"
  ): TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSourceCode"
  ): TypedContractMethod<[_sourceCode: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSubscriptionId"
  ): TypedContractMethod<[_subscriptionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sourceCode"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "subscriptionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RequestFulfilled"
  ): TypedContractEvent<
    RequestFulfilledEvent.InputTuple,
    RequestFulfilledEvent.OutputTuple,
    RequestFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "RequestSent"
  ): TypedContractEvent<
    RequestSentEvent.InputTuple,
    RequestSentEvent.OutputTuple,
    RequestSentEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoreFulfilled"
  ): TypedContractEvent<
    RiskScoreFulfilledEvent.InputTuple,
    RiskScoreFulfilledEvent.OutputTuple,
    RiskScoreFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoreRequested"
  ): TypedContractEvent<
    RiskScoreRequestedEvent.InputTuple,
    RiskScoreRequestedEvent.OutputTuple,
    RiskScoreRequestedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RequestFulfilled(bytes32)": TypedContractEvent<
      RequestFulfilledEvent.InputTuple,
      RequestFulfilledEvent.OutputTuple,
      RequestFulfilledEvent.OutputObject
    >;
    RequestFulfilled: TypedContractEvent<
      RequestFulfilledEvent.InputTuple,
      RequestFulfilledEvent.OutputTuple,
      RequestFulfilledEvent.OutputObject
    >;

    "RequestSent(bytes32)": TypedContractEvent<
      RequestSentEvent.InputTuple,
      RequestSentEvent.OutputTuple,
      RequestSentEvent.OutputObject
    >;
    RequestSent: TypedContractEvent<
      RequestSentEvent.InputTuple,
      RequestSentEvent.OutputTuple,
      RequestSentEvent.OutputObject
    >;

    "RiskScoreFulfilled(bytes32,uint256)": TypedContractEvent<
      RiskScoreFulfilledEvent.InputTuple,
      RiskScoreFulfilledEvent.OutputTuple,
      RiskScoreFulfilledEvent.OutputObject
    >;
    RiskScoreFulfilled: TypedContractEvent<
      RiskScoreFulfilledEvent.InputTuple,
      RiskScoreFulfilledEvent.OutputTuple,
      RiskScoreFulfilledEvent.OutputObject
    >;

    "RiskScoreRequested(bytes32,int256,int256,bytes32)": TypedContractEvent<
      RiskScoreRequestedEvent.InputTuple,
      RiskScoreRequestedEvent.OutputTuple,
      RiskScoreRequestedEvent.OutputObject
    >;
    RiskScoreRequested: TypedContractEvent<
      RiskScoreRequestedEvent.InputTuple,
      RiskScoreRequestedEvent.OutputTuple,
      RiskScoreRequestedEvent.OutputObject
    >;
  };
}
