/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ParametricVault {
  export type CampaignStruct = {
    id: BigNumberish;
    name: string;
    description: string;
    targetAmount: BigNumberish;
    raisedAmount: BigNumberish;
    deadline: BigNumberish;
    geoHash: BytesLike;
    status: BigNumberish;
    createdAt: BigNumberish;
    closedAt: BigNumberish;
  };

  export type CampaignStructOutput = [
    id: bigint,
    name: string,
    description: string,
    targetAmount: bigint,
    raisedAmount: bigint,
    deadline: bigint,
    geoHash: string,
    status: bigint,
    createdAt: bigint,
    closedAt: bigint
  ] & {
    id: bigint;
    name: string;
    description: string;
    targetAmount: bigint;
    raisedAmount: bigint;
    deadline: bigint;
    geoHash: string;
    status: bigint;
    createdAt: bigint;
    closedAt: bigint;
  };

  export type EmergencyEventStruct = {
    id: BigNumberish;
    disasterType: BytesLike;
    geoHash: BytesLike;
    startTime: BigNumberish;
    endTime: BigNumberish;
    fundsAllocated: BigNumberish;
    fundsDistributed: BigNumberish;
    isActive: boolean;
  };

  export type EmergencyEventStructOutput = [
    id: bigint,
    disasterType: string,
    geoHash: string,
    startTime: bigint,
    endTime: bigint,
    fundsAllocated: bigint,
    fundsDistributed: bigint,
    isActive: boolean
  ] & {
    id: bigint;
    disasterType: string;
    geoHash: string;
    startTime: bigint;
    endTime: bigint;
    fundsAllocated: bigint;
    fundsDistributed: bigint;
    isActive: boolean;
  };

  export type TaskStruct = {
    id: BigNumberish;
    description: string;
    reward: BigNumberish;
    volunteer: AddressLike;
    proofHash: BytesLike;
    status: BigNumberish;
    geoHash: BytesLike;
    createdAt: BigNumberish;
    claimedAt: BigNumberish;
    completedAt: BigNumberish;
  };

  export type TaskStructOutput = [
    id: bigint,
    description: string,
    reward: bigint,
    volunteer: string,
    proofHash: string,
    status: bigint,
    geoHash: string,
    createdAt: bigint,
    claimedAt: bigint,
    completedAt: bigint
  ] & {
    id: bigint;
    description: string;
    reward: bigint;
    volunteer: string;
    proofHash: string;
    status: bigint;
    geoHash: string;
    createdAt: bigint;
    claimedAt: bigint;
    completedAt: bigint;
  };
}

export interface ParametricVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DAO_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_ACTIVE_CAMPAIGNS"
      | "MAX_FEE_BPS"
      | "MAX_TVL"
      | "MIN_CAMPAIGN_TARGET"
      | "ORACLE_ROLE"
      | "activeCampaignCount"
      | "alertThreshold"
      | "campaignDonorBalances"
      | "campaigns"
      | "cancelTask"
      | "claimTask"
      | "closeCampaign"
      | "createCampaign"
      | "createTask"
      | "currentState"
      | "declareEmergencyByDAO"
      | "deposit"
      | "depositToCampaign"
      | "donorBalances"
      | "emergencies"
      | "emergencyReleasePercentage"
      | "emergencyThreshold"
      | "getAvailableFunds"
      | "getCampaign"
      | "getCampaignCount"
      | "getCampaignDonorBalance"
      | "getEmergency"
      | "getProtocolFeeInfo"
      | "getRoleAdmin"
      | "getTask"
      | "getTaskCount"
      | "getVaultBalance"
      | "grantRole"
      | "hasRole"
      | "latestRiskScore"
      | "pause"
      | "paused"
      | "protocolFeeBps"
      | "renounceRole"
      | "resetToIdle"
      | "revokeRole"
      | "setEmergencyReleasePercentage"
      | "setProtocolFee"
      | "setThresholds"
      | "setTreasury"
      | "settleEmergency"
      | "stablecoin"
      | "submitProof"
      | "supportsInterface"
      | "tasks"
      | "totalDeposits"
      | "totalFeesCollected"
      | "totalReleased"
      | "totalTaskPayouts"
      | "treasury"
      | "unpause"
      | "updateRiskScore"
      | "verifyAndPay"
      | "volunteerEarnings"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignClosed"
      | "CampaignCreated"
      | "CampaignDeposit"
      | "Deposited"
      | "EmergencyDeclared"
      | "EmergencyDeclaredByDAO"
      | "EmergencySettled"
      | "FeeCollected"
      | "FundsReleased"
      | "Paused"
      | "ProtocolFeeUpdated"
      | "RiskScoreUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StateChanged"
      | "TaskCancelled"
      | "TaskClaimed"
      | "TaskCreated"
      | "TaskProofSubmitted"
      | "TaskVerified"
      | "TreasuryUpdated"
      | "Unpaused"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DAO_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ACTIVE_CAMPAIGNS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_TVL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_CAMPAIGN_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeCampaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "alertThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignDonorBalances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "declareEmergencyByDAO",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToCampaign",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donorBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyReleasePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignDonorBalance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmergency",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolFeeInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestRiskScore",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetToIdle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyReleasePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setThresholds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleEmergency",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "totalDeposits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTaskPayouts",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateRiskScore",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndPay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "volunteerEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DAO_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ACTIVE_CAMPAIGNS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_TVL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_CAMPAIGN_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeCampaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "alertThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignDonorBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "declareEmergencyByDAO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donorBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyReleasePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignDonorBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolFeeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetToIdle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyReleasePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTaskPayouts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndPay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "volunteerEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CampaignClosedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    totalRaised: BigNumberish,
    reason: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    totalRaised: bigint,
    reason: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    totalRaised: bigint;
    reason: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    name: string,
    targetAmount: BigNumberish,
    geoHash: BytesLike
  ];
  export type OutputTuple = [
    campaignId: bigint,
    name: string,
    targetAmount: bigint,
    geoHash: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    name: string;
    targetAmount: bigint;
    geoHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignDepositEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [campaignId: bigint, donor: string, amount: bigint];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [donor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [donor: string, amount: bigint];
  export interface OutputObject {
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyDeclaredEvent {
  export type InputTuple = [
    emergencyId: BigNumberish,
    disasterType: BytesLike,
    fundsAllocated: BigNumberish
  ];
  export type OutputTuple = [
    emergencyId: bigint,
    disasterType: string,
    fundsAllocated: bigint
  ];
  export interface OutputObject {
    emergencyId: bigint;
    disasterType: string;
    fundsAllocated: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyDeclaredByDAOEvent {
  export type InputTuple = [
    disasterType: BytesLike,
    geoHash: BytesLike,
    evidence: string,
    declarer: AddressLike
  ];
  export type OutputTuple = [
    disasterType: string,
    geoHash: string,
    evidence: string,
    declarer: string
  ];
  export interface OutputObject {
    disasterType: string;
    geoHash: string;
    evidence: string;
    declarer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencySettledEvent {
  export type InputTuple = [
    emergencyId: BigNumberish,
    totalDistributed: BigNumberish
  ];
  export type OutputTuple = [emergencyId: bigint, totalDistributed: bigint];
  export interface OutputObject {
    emergencyId: bigint;
    totalDistributed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [
    donor: AddressLike,
    feeAmount: BigNumberish,
    netAmount: BigNumberish
  ];
  export type OutputTuple = [
    donor: string,
    feeAmount: bigint,
    netAmount: bigint
  ];
  export interface OutputObject {
    donor: string;
    feeAmount: bigint;
    netAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [amount: BigNumberish, reason: string];
  export type OutputTuple = [amount: bigint, reason: string];
  export interface OutputObject {
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoreUpdatedEvent {
  export type InputTuple = [
    severity: BigNumberish,
    disasterType: BytesLike,
    geoHash: BytesLike
  ];
  export type OutputTuple = [
    severity: bigint,
    disasterType: string,
    geoHash: string
  ];
  export interface OutputObject {
    severity: bigint;
    disasterType: string;
    geoHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StateChangedEvent {
  export type InputTuple = [oldState: BigNumberish, newState: BigNumberish];
  export type OutputTuple = [oldState: bigint, newState: bigint];
  export interface OutputObject {
    oldState: bigint;
    newState: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskClaimedEvent {
  export type InputTuple = [taskId: BigNumberish, volunteer: AddressLike];
  export type OutputTuple = [taskId: bigint, volunteer: string];
  export interface OutputObject {
    taskId: bigint;
    volunteer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    description: string,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    description: string,
    reward: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    description: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskProofSubmittedEvent {
  export type InputTuple = [taskId: BigNumberish, proofHash: BytesLike];
  export type OutputTuple = [taskId: bigint, proofHash: string];
  export interface OutputObject {
    taskId: bigint;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskVerifiedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    volunteer: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, volunteer: string, reward: bigint];
  export interface OutputObject {
    taskId: bigint;
    volunteer: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [donor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [donor: string, amount: bigint];
  export interface OutputObject {
    donor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ParametricVault extends BaseContract {
  connect(runner?: ContractRunner | null): ParametricVault;
  waitForDeployment(): Promise<this>;

  interface: ParametricVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DAO_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_ACTIVE_CAMPAIGNS: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_TVL: TypedContractMethod<[], [bigint], "view">;

  MIN_CAMPAIGN_TARGET: TypedContractMethod<[], [bigint], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  activeCampaignCount: TypedContractMethod<[], [bigint], "view">;

  alertThreshold: TypedContractMethod<[], [bigint], "view">;

  campaignDonorBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        name: string;
        description: string;
        targetAmount: bigint;
        raisedAmount: bigint;
        deadline: bigint;
        geoHash: string;
        status: bigint;
        createdAt: bigint;
        closedAt: bigint;
      }
    ],
    "view"
  >;

  cancelTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  claimTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  closeCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [
      name: string,
      description: string,
      targetAmount: BigNumberish,
      deadline: BigNumberish,
      geoHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [description: string, reward: BigNumberish, geoHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  currentState: TypedContractMethod<[], [bigint], "view">;

  declareEmergencyByDAO: TypedContractMethod<
    [disasterType: BytesLike, geoHash: BytesLike, evidence: string],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  depositToCampaign: TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  donorBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  emergencies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        disasterType: string;
        geoHash: string;
        startTime: bigint;
        endTime: bigint;
        fundsAllocated: bigint;
        fundsDistributed: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  emergencyReleasePercentage: TypedContractMethod<[], [bigint], "view">;

  emergencyThreshold: TypedContractMethod<[], [bigint], "view">;

  getAvailableFunds: TypedContractMethod<[], [bigint], "view">;

  getCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [ParametricVault.CampaignStructOutput],
    "view"
  >;

  getCampaignCount: TypedContractMethod<[], [bigint], "view">;

  getCampaignDonorBalance: TypedContractMethod<
    [campaignId: BigNumberish, donor: AddressLike],
    [bigint],
    "view"
  >;

  getEmergency: TypedContractMethod<
    [emergencyId: BigNumberish],
    [ParametricVault.EmergencyEventStructOutput],
    "view"
  >;

  getProtocolFeeInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, string, bigint] & {
        feeBps: bigint;
        maxFeeBps: bigint;
        treasuryAddr: string;
        totalCollected: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [ParametricVault.TaskStructOutput],
    "view"
  >;

  getTaskCount: TypedContractMethod<[], [bigint], "view">;

  getVaultBalance: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  latestRiskScore: TypedContractMethod<
    [],
    [
      [bigint, string, string, bigint] & {
        severity: bigint;
        disasterType: string;
        geoHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  protocolFeeBps: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  resetToIdle: TypedContractMethod<[], [void], "nonpayable">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setEmergencyReleasePercentage: TypedContractMethod<
    [newPercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProtocolFee: TypedContractMethod<
    [_feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setThresholds: TypedContractMethod<
    [_alertThreshold: BigNumberish, _emergencyThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  settleEmergency: TypedContractMethod<
    [emergencyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  stablecoin: TypedContractMethod<[], [string], "view">;

  submitProof: TypedContractMethod<
    [taskId: BigNumberish, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        description: string;
        reward: bigint;
        volunteer: string;
        proofHash: string;
        status: bigint;
        geoHash: string;
        createdAt: bigint;
        claimedAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;

  totalDeposits: TypedContractMethod<[], [bigint], "view">;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  totalReleased: TypedContractMethod<[], [bigint], "view">;

  totalTaskPayouts: TypedContractMethod<[], [bigint], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateRiskScore: TypedContractMethod<
    [severity: BigNumberish, disasterType: BytesLike, geoHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyAndPay: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  volunteerEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DAO_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_ACTIVE_CAMPAIGNS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TVL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_CAMPAIGN_TARGET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeCampaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "alertThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaignDonorBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        name: string;
        description: string;
        targetAmount: bigint;
        raisedAmount: bigint;
        deadline: bigint;
        geoHash: string;
        status: bigint;
        createdAt: bigint;
        closedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closeCampaign"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      targetAmount: BigNumberish,
      deadline: BigNumberish,
      geoHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [description: string, reward: BigNumberish, geoHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "declareEmergencyByDAO"
  ): TypedContractMethod<
    [disasterType: BytesLike, geoHash: BytesLike, evidence: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositToCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donorBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        disasterType: string;
        geoHash: string;
        startTime: bigint;
        endTime: bigint;
        fundsAllocated: bigint;
        fundsDistributed: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyReleasePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAvailableFunds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [ParametricVault.CampaignStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCampaignDonorBalance"
  ): TypedContractMethod<
    [campaignId: BigNumberish, donor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEmergency"
  ): TypedContractMethod<
    [emergencyId: BigNumberish],
    [ParametricVault.EmergencyEventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProtocolFeeInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, string, bigint] & {
        feeBps: bigint;
        maxFeeBps: bigint;
        treasuryAddr: string;
        totalCollected: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [ParametricVault.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaultBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestRiskScore"
  ): TypedContractMethod<
    [],
    [
      [bigint, string, string, bigint] & {
        severity: bigint;
        disasterType: string;
        geoHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resetToIdle"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEmergencyReleasePercentage"
  ): TypedContractMethod<[newPercentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFee"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setThresholds"
  ): TypedContractMethod<
    [_alertThreshold: BigNumberish, _emergencyThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleEmergency"
  ): TypedContractMethod<[emergencyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [taskId: BigNumberish, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        description: string;
        reward: bigint;
        volunteer: string;
        proofHash: string;
        status: bigint;
        geoHash: string;
        createdAt: bigint;
        claimedAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalDeposits"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalTaskPayouts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRiskScore"
  ): TypedContractMethod<
    [severity: BigNumberish, disasterType: BytesLike, geoHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAndPay"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "volunteerEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CampaignClosed"
  ): TypedContractEvent<
    CampaignClosedEvent.InputTuple,
    CampaignClosedEvent.OutputTuple,
    CampaignClosedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignDeposit"
  ): TypedContractEvent<
    CampaignDepositEvent.InputTuple,
    CampaignDepositEvent.OutputTuple,
    CampaignDepositEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyDeclared"
  ): TypedContractEvent<
    EmergencyDeclaredEvent.InputTuple,
    EmergencyDeclaredEvent.OutputTuple,
    EmergencyDeclaredEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyDeclaredByDAO"
  ): TypedContractEvent<
    EmergencyDeclaredByDAOEvent.InputTuple,
    EmergencyDeclaredByDAOEvent.OutputTuple,
    EmergencyDeclaredByDAOEvent.OutputObject
  >;
  getEvent(
    key: "EmergencySettled"
  ): TypedContractEvent<
    EmergencySettledEvent.InputTuple,
    EmergencySettledEvent.OutputTuple,
    EmergencySettledEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeeUpdated"
  ): TypedContractEvent<
    ProtocolFeeUpdatedEvent.InputTuple,
    ProtocolFeeUpdatedEvent.OutputTuple,
    ProtocolFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoreUpdated"
  ): TypedContractEvent<
    RiskScoreUpdatedEvent.InputTuple,
    RiskScoreUpdatedEvent.OutputTuple,
    RiskScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StateChanged"
  ): TypedContractEvent<
    StateChangedEvent.InputTuple,
    StateChangedEvent.OutputTuple,
    StateChangedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskClaimed"
  ): TypedContractEvent<
    TaskClaimedEvent.InputTuple,
    TaskClaimedEvent.OutputTuple,
    TaskClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskProofSubmitted"
  ): TypedContractEvent<
    TaskProofSubmittedEvent.InputTuple,
    TaskProofSubmittedEvent.OutputTuple,
    TaskProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TaskVerified"
  ): TypedContractEvent<
    TaskVerifiedEvent.InputTuple,
    TaskVerifiedEvent.OutputTuple,
    TaskVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "CampaignClosed(uint256,uint256,uint8)": TypedContractEvent<
      CampaignClosedEvent.InputTuple,
      CampaignClosedEvent.OutputTuple,
      CampaignClosedEvent.OutputObject
    >;
    CampaignClosed: TypedContractEvent<
      CampaignClosedEvent.InputTuple,
      CampaignClosedEvent.OutputTuple,
      CampaignClosedEvent.OutputObject
    >;

    "CampaignCreated(uint256,string,uint256,bytes32)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignDeposit(uint256,address,uint256)": TypedContractEvent<
      CampaignDepositEvent.InputTuple,
      CampaignDepositEvent.OutputTuple,
      CampaignDepositEvent.OutputObject
    >;
    CampaignDeposit: TypedContractEvent<
      CampaignDepositEvent.InputTuple,
      CampaignDepositEvent.OutputTuple,
      CampaignDepositEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "EmergencyDeclared(uint256,bytes32,uint256)": TypedContractEvent<
      EmergencyDeclaredEvent.InputTuple,
      EmergencyDeclaredEvent.OutputTuple,
      EmergencyDeclaredEvent.OutputObject
    >;
    EmergencyDeclared: TypedContractEvent<
      EmergencyDeclaredEvent.InputTuple,
      EmergencyDeclaredEvent.OutputTuple,
      EmergencyDeclaredEvent.OutputObject
    >;

    "EmergencyDeclaredByDAO(bytes32,bytes32,string,address)": TypedContractEvent<
      EmergencyDeclaredByDAOEvent.InputTuple,
      EmergencyDeclaredByDAOEvent.OutputTuple,
      EmergencyDeclaredByDAOEvent.OutputObject
    >;
    EmergencyDeclaredByDAO: TypedContractEvent<
      EmergencyDeclaredByDAOEvent.InputTuple,
      EmergencyDeclaredByDAOEvent.OutputTuple,
      EmergencyDeclaredByDAOEvent.OutputObject
    >;

    "EmergencySettled(uint256,uint256)": TypedContractEvent<
      EmergencySettledEvent.InputTuple,
      EmergencySettledEvent.OutputTuple,
      EmergencySettledEvent.OutputObject
    >;
    EmergencySettled: TypedContractEvent<
      EmergencySettledEvent.InputTuple,
      EmergencySettledEvent.OutputTuple,
      EmergencySettledEvent.OutputObject
    >;

    "FeeCollected(address,uint256,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FundsReleased(uint256,string)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProtocolFeeUpdated(uint256,uint256)": TypedContractEvent<
      ProtocolFeeUpdatedEvent.InputTuple,
      ProtocolFeeUpdatedEvent.OutputTuple,
      ProtocolFeeUpdatedEvent.OutputObject
    >;
    ProtocolFeeUpdated: TypedContractEvent<
      ProtocolFeeUpdatedEvent.InputTuple,
      ProtocolFeeUpdatedEvent.OutputTuple,
      ProtocolFeeUpdatedEvent.OutputObject
    >;

    "RiskScoreUpdated(uint8,bytes32,bytes32)": TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;
    RiskScoreUpdated: TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StateChanged(uint8,uint8)": TypedContractEvent<
      StateChangedEvent.InputTuple,
      StateChangedEvent.OutputTuple,
      StateChangedEvent.OutputObject
    >;
    StateChanged: TypedContractEvent<
      StateChangedEvent.InputTuple,
      StateChangedEvent.OutputTuple,
      StateChangedEvent.OutputObject
    >;

    "TaskCancelled(uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskClaimed(uint256,address)": TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;
    TaskClaimed: TypedContractEvent<
      TaskClaimedEvent.InputTuple,
      TaskClaimedEvent.OutputTuple,
      TaskClaimedEvent.OutputObject
    >;

    "TaskCreated(uint256,string,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskProofSubmitted(uint256,bytes32)": TypedContractEvent<
      TaskProofSubmittedEvent.InputTuple,
      TaskProofSubmittedEvent.OutputTuple,
      TaskProofSubmittedEvent.OutputObject
    >;
    TaskProofSubmitted: TypedContractEvent<
      TaskProofSubmittedEvent.InputTuple,
      TaskProofSubmittedEvent.OutputTuple,
      TaskProofSubmittedEvent.OutputObject
    >;

    "TaskVerified(uint256,address,uint256)": TypedContractEvent<
      TaskVerifiedEvent.InputTuple,
      TaskVerifiedEvent.OutputTuple,
      TaskVerifiedEvent.OutputObject
    >;
    TaskVerified: TypedContractEvent<
      TaskVerifiedEvent.InputTuple,
      TaskVerifiedEvent.OutputTuple,
      TaskVerifiedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
