/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface YieldControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAO_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "calculateYieldAllocation"
      | "deployToYield"
      | "getConfig"
      | "getRoleAdmin"
      | "getYieldStats"
      | "grantRole"
      | "harvestYield"
      | "hasRole"
      | "liquidRatio"
      | "renounceRole"
      | "revokeRole"
      | "setRatios"
      | "setTreasury"
      | "setTreasuryYieldShare"
      | "setVault"
      | "stablecoin"
      | "supportsInterface"
      | "totalInYield"
      | "totalYieldEarned"
      | "totalYieldToTreasury"
      | "treasury"
      | "treasuryYieldShare"
      | "vault"
      | "withdrawFromYield"
      | "yieldRatio"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsDeployedToYield"
      | "FundsWithdrawnFromYield"
      | "RatioUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TreasuryShareUpdated"
      | "YieldHarvested"
  ): EventFragment;

  encodeFunctionData(functionFragment: "DAO_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateYieldAllocation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployToYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getYieldStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "harvestYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRatios",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryYieldShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalInYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalYieldEarned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalYieldToTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treasuryYieldShare",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFromYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldRatio",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "DAO_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateYieldAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployToYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYieldStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "harvestYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRatios", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryYieldShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalInYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalYieldEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalYieldToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryYieldShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yieldRatio", data: BytesLike): Result;
}

export namespace FundsDeployedToYieldEvent {
  export type InputTuple = [amount: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [amount: bigint, timestamp: bigint];
  export interface OutputObject {
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnFromYieldEvent {
  export type InputTuple = [amount: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [amount: bigint, timestamp: bigint];
  export interface OutputObject {
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatioUpdatedEvent {
  export type InputTuple = [
    liquidRatio: BigNumberish,
    yieldRatio: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    liquidRatio: bigint,
    yieldRatio: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    liquidRatio: bigint;
    yieldRatio: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryShareUpdatedEvent {
  export type InputTuple = [
    oldShare: BigNumberish,
    newShare: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    oldShare: bigint,
    newShare: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    oldShare: bigint;
    newShare: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldHarvestedEvent {
  export type InputTuple = [
    totalYield: BigNumberish,
    toTreasury: BigNumberish,
    toVault: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    totalYield: bigint,
    toTreasury: bigint,
    toVault: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    totalYield: bigint;
    toTreasury: bigint;
    toVault: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YieldController extends BaseContract {
  connect(runner?: ContractRunner | null): YieldController;
  waitForDeployment(): Promise<this>;

  interface: YieldControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAO_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  calculateYieldAllocation: TypedContractMethod<
    [depositAmount: BigNumberish],
    [[bigint, bigint] & { liquidAmount: bigint; yieldAmount: bigint }],
    "view"
  >;

  deployToYield: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getConfig: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string, string] & {
        _liquidRatio: bigint;
        _yieldRatio: bigint;
        _treasuryYieldShare: bigint;
        _vault: string;
        _treasury: string;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getYieldStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalInYield: bigint;
        _totalYieldEarned: bigint;
        _totalYieldToTreasury: bigint;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  harvestYield: TypedContractMethod<[], [void], "nonpayable">;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  liquidRatio: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setRatios: TypedContractMethod<
    [_liquidRatio: BigNumberish, _yieldRatio: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasuryYieldShare: TypedContractMethod<
    [_newShare: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVault: TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;

  stablecoin: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalInYield: TypedContractMethod<[], [bigint], "view">;

  totalYieldEarned: TypedContractMethod<[], [bigint], "view">;

  totalYieldToTreasury: TypedContractMethod<[], [bigint], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  treasuryYieldShare: TypedContractMethod<[], [bigint], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  withdrawFromYield: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  yieldRatio: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAO_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculateYieldAllocation"
  ): TypedContractMethod<
    [depositAmount: BigNumberish],
    [[bigint, bigint] & { liquidAmount: bigint; yieldAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "deployToYield"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getConfig"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string, string] & {
        _liquidRatio: bigint;
        _yieldRatio: bigint;
        _treasuryYieldShare: bigint;
        _vault: string;
        _treasury: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getYieldStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalInYield: bigint;
        _totalYieldEarned: bigint;
        _totalYieldToTreasury: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "harvestYield"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRatios"
  ): TypedContractMethod<
    [_liquidRatio: BigNumberish, _yieldRatio: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasuryYieldShare"
  ): TypedContractMethod<[_newShare: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVault"
  ): TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalInYield"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalYieldEarned"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalYieldToTreasury"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasuryYieldShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawFromYield"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "yieldRatio"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FundsDeployedToYield"
  ): TypedContractEvent<
    FundsDeployedToYieldEvent.InputTuple,
    FundsDeployedToYieldEvent.OutputTuple,
    FundsDeployedToYieldEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawnFromYield"
  ): TypedContractEvent<
    FundsWithdrawnFromYieldEvent.InputTuple,
    FundsWithdrawnFromYieldEvent.OutputTuple,
    FundsWithdrawnFromYieldEvent.OutputObject
  >;
  getEvent(
    key: "RatioUpdated"
  ): TypedContractEvent<
    RatioUpdatedEvent.InputTuple,
    RatioUpdatedEvent.OutputTuple,
    RatioUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryShareUpdated"
  ): TypedContractEvent<
    TreasuryShareUpdatedEvent.InputTuple,
    TreasuryShareUpdatedEvent.OutputTuple,
    TreasuryShareUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "YieldHarvested"
  ): TypedContractEvent<
    YieldHarvestedEvent.InputTuple,
    YieldHarvestedEvent.OutputTuple,
    YieldHarvestedEvent.OutputObject
  >;

  filters: {
    "FundsDeployedToYield(uint256,uint256)": TypedContractEvent<
      FundsDeployedToYieldEvent.InputTuple,
      FundsDeployedToYieldEvent.OutputTuple,
      FundsDeployedToYieldEvent.OutputObject
    >;
    FundsDeployedToYield: TypedContractEvent<
      FundsDeployedToYieldEvent.InputTuple,
      FundsDeployedToYieldEvent.OutputTuple,
      FundsDeployedToYieldEvent.OutputObject
    >;

    "FundsWithdrawnFromYield(uint256,uint256)": TypedContractEvent<
      FundsWithdrawnFromYieldEvent.InputTuple,
      FundsWithdrawnFromYieldEvent.OutputTuple,
      FundsWithdrawnFromYieldEvent.OutputObject
    >;
    FundsWithdrawnFromYield: TypedContractEvent<
      FundsWithdrawnFromYieldEvent.InputTuple,
      FundsWithdrawnFromYieldEvent.OutputTuple,
      FundsWithdrawnFromYieldEvent.OutputObject
    >;

    "RatioUpdated(uint256,uint256,address)": TypedContractEvent<
      RatioUpdatedEvent.InputTuple,
      RatioUpdatedEvent.OutputTuple,
      RatioUpdatedEvent.OutputObject
    >;
    RatioUpdated: TypedContractEvent<
      RatioUpdatedEvent.InputTuple,
      RatioUpdatedEvent.OutputTuple,
      RatioUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TreasuryShareUpdated(uint256,uint256,address)": TypedContractEvent<
      TreasuryShareUpdatedEvent.InputTuple,
      TreasuryShareUpdatedEvent.OutputTuple,
      TreasuryShareUpdatedEvent.OutputObject
    >;
    TreasuryShareUpdated: TypedContractEvent<
      TreasuryShareUpdatedEvent.InputTuple,
      TreasuryShareUpdatedEvent.OutputTuple,
      TreasuryShareUpdatedEvent.OutputObject
    >;

    "YieldHarvested(uint256,uint256,uint256,uint256)": TypedContractEvent<
      YieldHarvestedEvent.InputTuple,
      YieldHarvestedEvent.OutputTuple,
      YieldHarvestedEvent.OutputObject
    >;
    YieldHarvested: TypedContractEvent<
      YieldHarvestedEvent.InputTuple,
      YieldHarvestedEvent.OutputTuple,
      YieldHarvestedEvent.OutputObject
    >;
  };
}
